### ISSUE TITLE
ARM and ARM64 support

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1153]
Roadmap for ARM support:

- [x] Fix CMakeFiles
- [x] Remove external unwind #676 
- [x] Fix alignment issues with msgpuck https://github.com/rtsisyk/msgpuck/issues/2 
- [x] Fix msgpackffi.lua
- [x] Return aligned addresses from region_alloc() https://github.com/tarantool/small/issues/1 
- [x] Properly configure libcoro to don't use signals (use `swapcontext()` or find a better option) on ARM/ARM64 (see also #1152)
- [x] Fix or remove mhash #1110 
- [ ] Add `armhf` binary packages for Debian, Ubuntu, Fedora, CentOS(?)

--- 1.6.8 cut off ---

- [x] Assembler implementation of `coro_transfer()` #1152 - complicated, may take a long time
- [ ] `arm64` (`aarch64`) packages for Debian, Ubuntu, Fedora, CentOS(?) - hardware is not available yet

**Comment by gpryor** [comment]
Please let me know how I can contribute to this effort as a non-developer.

**Comment by rtsisyk** [comment]
Finished.
Please see also packing task https://github.com/tarantool/tarantool/issues/1184
