### ISSUE TITLE
1.8 alpha

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1209]
Flagship:
- [ ] https://github.com/tarantool/tarantool/issues/980 bsync - alpha 1
- [x] https://github.com/tarantool/tarantool/issues/1059 sql on a single node - alpha 2

Rolling:
- [ ] https://github.com/tarantool/tarantool/issues/1257 extend data type support in indexed columns
- [ ] https://github.com/tarantool/tarantool/issues/1251 new alloc for tuples (unlimited tuple size)
- [ ] https://github.com/tarantool/tarantool/issues/1252 new light hash
- [ ] https://github.com/tarantool/tarantool/issues/1254 parallel applier in async
- [x] https://github.com/tarantool/tarantool/issues/1213 new background mode
- [x] https://github.com/tarantool/tarantool/issues/775 new local hot standby mode

**Comment by kostja** [comment]
This plan is not relevant any more.
