### ISSUE TITLE
1.7 alpha 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1526]
Flagship feature - disk engine (phia):

- [x] Refactor code to use Tarantool code style and data structures #1452
- [x] Fix O(n) complexity of get()
- [ ] Refactor merger
- [x] Switch to key_def and  MessagePack format
- [ ] Secondary keys support
- [x] New JOIN implementation #1239
- [x] Remove unused features, increase coverage to 90% #1484
- [ ] Fix [bugs](https://github.com/tarantool/tarantool/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A1.7.0 ) and [crashes](https://github.com/tarantool/tarantool/issues?q=is%3Aopen+is%3Aissue+label%3Acrash+milestone%3A1.7.0) 

## Fix O(n) complexity of get()

- [ ] Investigate how si_range() works @alyapunov 
- [x] Fix --long tests performance - O(n) complexity on get() @alyapunov 
- [ ] Fix transaction conflicts caused by usage of si_range() instead of si_get() @alyapunov 
- [ ] remove scheduler.lru option @alyapunov 

## Refactor merger

- [ ] Investigate how merger works @kostja 
- [ ] compaction options in phia (zones) settable from the config file @kostja 
- [x] try to remove bufiter @kostja 
- [ ] remove buffer @kostja 

```
* struct PACKED svmergeiter
* struct PACKED svreaditer
* struct PACKED svwriteiter
* struct PACKED svindexiter
* struct PACKED sdpageiter
* struct PACKED sdindexiter
* struct PACKED siiter
* struct ssiter
* struct ssbufiter
```

## Switch to key_def and MessagePack format

- [x] remove phia_document @rtsisyk
- [x] remove SS_U32, SS_U32PREV, SS_I64, SS_U64REV types from indexes. @rtsisyk
- [x] implement iteration over a partial key  @rtsisyk
- [x] allow up to 32 key parts, like in memtx @rtsisyk
- [ ] allow key parts to have gaps 
- [ ] fix upsert madness
- [ ] add checks that storage format version doesn't match tarantool version

## Switch to Tarantool allocators

- [ ] switch to Tarantool allocators @GeorgyKirichenko 

## Other

- [ ] re-implement range-index snapshot in a way that doesn't lock the range index node while the snapshot is taken.
- [ ] add test cases for min(), max()
- [ ] add test cases for count()
- [ ] fix truncate

**Comment by rtsisyk** [comment]
Splitted to individual tickets.
