### ISSUE TITLE
Vinyl gamma todo

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1792]
- [x] speed up vinyl tests: scrutinize every long test and extract every bit of performance from it => #1918
- [x] multi-level ranges (1:100 case) => #1821
- [x] remove range size => #1915
- [x] remove page size, run size => #1915
- [x] vy_mem should be using either slab or region alloc => #1907
- [x] new scheduler: a trade-off between read and write amplification, throttling => #1862
- [x] move snapshot daemon into an own thread, harmonize with vinyl garbage collection to make backups possible; add a test case for backup => #1916
- [x] snapshot daemon every hour forces dump of every vinyl range - this creates absurdly small runs - find a solution for that => #1916
- [x] make sure range splits don't break time-series use case => #1917
- [x] use slab allocator for vinyl index pages => #1767
- [x] rewrite vy_index_bsize() to be simpler than it is now? => 94da1913640ff925535d465ca31aede4c40441fb
- [x] change run iterator api to avoid start and get; only next()
- [x] dump/merge failure or any oom event should eventually lead to vinyl becoming read-only  - yield timeouts in throttling should increase to infnity; this needs a test case
- [x] optimize write iterator to squash writes of non-active transactions (aka purge lsn becoming an array) => #1920
- [x] remove creation of range iterator in vy_tx_write(), simply look up the range in the tree
- [x] vy_index_get still reads the read view, not the latest lsn; fix the bugs reading the latest lsn introduces => #1866 
- [x] test cases for consistent read views
- [x] don't write tuple offsets to disk => #1759
- [x] remove offsets, use tarantool tuples or something similar => #1572
- [x] remove vinyl iterator types/vy_order => #1704
- [x] check return value of si_write, add test => #1842
- [x] remove si_readcommitted
- [x] prefix compression, especially for non-unique secondary keys: store the primary key once for all duplicates => #1819
- [x] remove secondary keys from conflict manager => #1908
- [x] replace clock_monotonic with fiber clock
- [x] bloom filters for every page => #1919
- [x] replica_join is broken with secondary keys: applySnapshotRow() for secondary keys on replica
- [x] too many open files:  close range file on LRU basis? Ignore it for now? => implement our own block storage
- [x] lru cache based on range index => #1692
- [x] remove only_disk, use merge iterator in vy_index_send => #1922

Big:
- [x] rewrite auto_increment in vinyl to use a persistent sequence stored in memtx engine; this requires that we have a) subtransactions/savepoints b) common tx manager for memtx and vinyl; but this will let us make auto_increment a CRDT operation in master-master if we add auto_increment offset/increment to sequence options => #1921

Need feedback:

- [x] vy_index_ref finish removing
- [x] double read of non-existing tuple - optimize to avoid disk lookup, important special case for max()/auto_increment/insert
- [x] implement savepoints for all engines; savepoint rollback doesn't release write lock in vinyl, and doesn't restore squashed upserts - it's a design issue
- [x] transaction read range bugs: lack of gap locks breaks repeatable read in range queries
- [x] tx isolation - provide repeatable read which is faster; - if tx->isolation = SNAPSHOT, do not track its
  reads in txvindex.

Done:
- [x] replica_join is broken: range list may change while join is in progress

**Comment by kostja** [comment]
Split to multiple tickets, closing.
