### ISSUE TITLE
Plugin API for tarantoolctl

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#2337]
Currently add support for adding custom packages/subcommands from installed luarocks.

### Overall plan

- [ ] Add needed functions to core of tarantool
- [ ] Add basic API for `tarantoolctl`
- [ ] Split old `tarantoolctl` into multiple files.
- [ ] Install new `tarantoolctl` and prepackaged modules in it's basic lua packages path (`/usr/share/tarantool/tarantoolctl/...`)
- [ ] ... (TBC)

### `string.*`/`table`/`pwd` functions

- [x] https://github.com/tarantool/tarantool/issues/2211 - `string.split()` Lua API (done in PR https://github.com/tarantool/tarantool/pull/2313)
- [x] https://github.com/tarantool/tarantool/issues/2212 - `table.deepcopy()` Lua API (done in PR https://github.com/tarantool/tarantool/pull/2323) 
- [ ] https://github.com/tarantool/tarantool/issues/2213 - `pwd` Lua module
- [x] https://github.com/tarantool/tarantool/issues/2214 - `string.ljust()`/`string.rjust()` Lua API (done in PR https://github.com/tarantool/tarantool/pull/2313)
- [x] https://github.com/tarantool/tarantool/issues/2215 - `string.startswith()`/`string.endswith()` Lua API (done in PR https://github.com/tarantool/tarantool/pull/2313)

**Comment by rtsisyk** [comment]
we don't have enough time to finish this feature in 1.7.5, moving to 1.7.6
