### ISSUE TITLE
Column definitions for SQL

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2652]
In order to support SQL standard we need to implement column definitions. This should include:
- [x] table ID
- [x] table name
- [x] is_temporary
- [x] column count
- [x] columns:
  - [x] column name
  - [x] column type:
    - [x] INTEGER
    - [x] UNSIGNED
    - [x] STRING
    - [x] FLOAT
    - [x] BLOB
    - [x] MAP
    - [x] ARRAY
    - [ ] <s> is_unique </s> -  @rtsisyk: should be derived from index definitions 
    - [ ] <s> NOT NULL </s> @rtsisyk: => https://github.com/tarantool/tarantool/issues/1557
    - [ ] <s> DEFAULT value </s> @rtsisyk: => https://github.com/tarantool/tarantool/issues/1557
    - [ ] <s> COLLATION (case, nocase)</s> => https://github.com/tarantool/tarantool/issues/2121
    - [ ] <s> SIZE [for ARRAY and MAP]</s> @rtsisyk => https://github.com/tarantool/tarantool/issues/1285

**Comment by rtsisyk** [comment]
Column definitions have been implemented. NULLS && DEFAULT, COLLATIONS and ARRAY SIZE are parts of other features.
