### ISSUE TITLE
Developer Tools and IDE support

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2731]
- [x] Add Lua 5.1 command-line options https://github.com/tarantool/tarantool/issues/1265
- [ ] Enable /usr/bin/tarantool as a Lua interpreter https://github.com/tarantool/tarantool/issues/2730
- [ ] Document how to use LuaJIT profiler
- [ ] Document how to configure [Lua](https://plugins.jetbrains.com/plugin/5055-lua) or [EmmyLua](https://plugins.jetbrains.com/plugin/9768-emmylua) plugin for IntelliJ Idea to use with Tarantool
- [ ] Document how to configure [Lua plugin](https://atom.io/packages/language-lua) for Atom
- [ ] Patch [ZeroBrain Studio](https://github.com/pkulchenko/ZeroBraneStudio) to support /usr/bin/tarantool and send a pull request
- [ ] Adapt ModDebug remote debugger https://github.com/tarantool/tarantool/issues/2728
- [ ] Add stubs for Lua API https://github.com/tarantool/tarantool/issues/2729
- [ ] Re-pack Lua or EmmyLua plugin with proper settings, our stubs and working debugger
- [ ] Document how to configure our brand new Tarantool plugin for IntelliJ idea from the previous step

**Comment by theonedemon** [comment]
any news ?

**Comment by ilyabreev** [comment]
Is there any updates on debugging lua in tarantool under Windows?

**Comment by Totktonada** [comment]
It worth to note that moddebug/emmylua are not integrated with fibers.
