### ISSUE TITLE
Rust as a second programming language 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2747]
This is umbrella ticket for feature called "second programming language for Tarantool".

Our long-term goal is to provide an alternative programming language for Tarantool. Lua is an easy-to-learn duck-typing dynamic scripting language, but one language doesn't fit all. Lua significantly reduces the development costs, but it doesn't allow to utilize Tarantool transaction engine at the full scale due to interpreter speed and sub-optimal garbage collector. 

Unfortunately, all other popular scripting languages, such JS or Python are not better in terms of performance when compared with LuaJIT (actually, they are worse). Therefore, the first criterion for me is that execution speed of applications should be close to native (C-like). Garbage collection, our second problem, is a technology which has never worked and will never work with predictable latency (see JVM changelog to get a proof). Therefore, the number two criterion for me is the predictable memory management, preferable automatic, but not GC-managed. C and C++ completely meets these criteria, but too complicated (read as "expensive") to develop business logic. The last but not least, a new programming language should be widely adapted by community, because we're not Microsoft or Sun to develop and popularize a new programming language, so don't advise us to add "Fua" instead of "Lua".

In my opinion, Swift and Rust are two good candidates to be a new C++  for humans. Since Swift support is already [implemented](https://github.com/tris-foundation/tarantool) by @tonyfreeman based on my and @antonmes PoC, this ticket is about [Rust Language](https://www.rust-lang.org/). Rust is a compiled strictly-typed language which uses [ownership transfer and borrowing semantics](https://doc.rust-lang.org/1.8.0/book/references-and-borrowing.html) for memory management.

- [x] Implement C API for DBMS - done in [1.6.4](4efe97b7b74874087caf1ade3514884ae72b3ba12)
- [x] Implement native stored procedures (box.schema.func.create()) - done in [1.6.6](https://github.com/tarantool/tarantool/issues/897)
- [x] Implement hot code reload for native procedures - done [1.7.5](https://github.com/tarantool/tarantool/releases/tag/1.7.5)
- [x] C <-> Rust bridge - done in [Rust PoC](https://github.com/rtsisyk/tarantool-rust/commit/3e56d26c895249c99f966de49478f8242de34921) (1.6.8)
- [x] Check that fiber switching is supported - [Rust PoC](https://github.com/rtsisyk/tarantool-rust/commit/3e56d26c895249c99f966de49478f8242de34921) (1.6.8)
- [x] Register "tarantool" crate in Cargo - [done](https://crates.io/crates/tarantool)
- [ ] Rust bindings for Logger API - https://github.com/rtsisyk/tarantool-rust/issues/3
- [ ] Rust bindings for Fiber API - https://github.com/rtsisyk/tarantool-rust/issues/2
- [ ] Find or write MessagePack encoder/decoder https://github.com/rtsisyk/tarantool-rust/issues/7
- [ ] Rust bindings for Box API (box.space) - https://github.com/rtsisyk/tarantool-rust/issues/1
- [ ] Adapt one of the existing Rust-to-Lua bindings to allow calling Lua from Rust
- [ ] Implement one or more Tarantool/Queue-like infrastructure module using Rust
- [ ] Think how to use our built-in LuaRocks to distribute Rust modules (should work for Rust as well)
- [ ] Implement one or more commercial solutions using Rust
- [ ] Adapt existing Rust developer tools and IDE to use with Tarantool - https://github.com/tarantool/tarantool/issues/2731
- [ ] Document that Rust should be used instead of Lua in some cases.

Please note that we don't intent to deprecate or remove Lua. The support for a new programming language will be added instead.

**Comment by aleclarson** [comment]
It looks like you're too far in to turn around, but I'm curious if [Wren](http://wren.io) was ever considered (and your thoughts on it)?

- Built-in fibers
- Performance details: http://wren.io/performance.html
- Simple syntax

Sorry, if this comment doesn't belong in this issue.

**Comment by zamazan4ik** [comment]
Just read an awesome article about Rust and Tarantool: https://habr.com/ru/company/oleg-bunin/blog/650991/

Could you simply rewrite Tarantool in Rust? It will make Rust a primary language instead of just secondary.

**Comment by FulgurIgor** [comment]
I totally agree with @zamazan4ik suggestion. I think that usage of c2rust utilite (https://github.com/immunant/c2rust) would be a great starting point for RIIR.
