### ISSUE TITLE
Modules and subprojects packaging meta-task (updating)

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#393]
All packaging related tasks across all tarantool/ repos

- [x]  https://github.com/tarantool/tarantool/issues/392 Unify package versions in Debian repository
- [x] Module build system (ticket will be added later)
- [x] https://github.com/tarantool/rocks/issues/2 An unified approach for testing modules
- [x] https://github.com/tarantool/rocks/issues/3 Add luarocks to tarantool build system
- [ ] https://github.com/tarantool/tarantool/issues/324 Move net.sql, net.pg, net,mysql to rocks

C:

- [ ] https://github.com/tarantool/tarantool-c/issues/4 Add tarantool-c to Tarantool buildbot

PHP:

- [x] https://github.com/tarantool/tarantool-php/issues/14 Add Travis configuration
- [x] https://github.com/tarantool/tarantool-php/issues/13 Add tarantool-php to Tarantool buildbot 

Python:
- [x] https://github.com/mailru/tarantool-python/issues/35 Add Travis configuration
- [x] https://github.com/mailru/tarantool-python/issues/36 Add tarantool-python to Tarantool buildbot 

Perl:

- [x] Repository must be moved to tarantool/ organization

Queue:
- [x] https://github.com/tarantool/queue/issues/6 Add TAP tests 
- [x] https://github.com/tarantool/queue/issues/5 Add Travis configuration
- [x] https://github.com/tarantool/queue/issues/7 Move non-Lua code to a new repository
- [x] https://github.com/tarantool/tarantool-queue-python/issues/5  Add tarantool-queue-python to Tarantool buildbot
- [ ] https://github.com/tarantool/tarantool-queue-python/issues/6 Add Travis configuration

Expirationd:

- [x] https://github.com/tarantool/expirationd/issues/3  Add TAP tests 
- [x] https://github.com/tarantool/expirationd/issues/2 Add Travis configuration

**Comment by kostja** [comment]
Closing this as most of this is done.
