### ISSUE TITLE
Integrate VShard into the core

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3996]
## Storage, track 1, replicaset- and cluster-wide spaces:
- [ ] #3981 - Rename 'replicaset' to 'cluster' in some internal function, variable and constant names;
- [ ] #3982 - New cluster-wide replication group;
- [ ] #3983 - Allow huge cluster size, blocked by #3982;
- [ ] #3984 - Get rid of cluster full mesh, blocked by #3983.

## Storage, track 2, native support of bucket id:
- [ ] #3985 - Introduce system tuple fields;
- [ ] #3986 - Introduce _bucket system space;
- [ ] #3987 - Allow to specify/create a partitioning index on an ordinary space, blocked by #3986, #3985;
- [ ] #3988 - Implement bucket_send function, blocked by #3986.

## Storage, track 3, sharding algorithms:
- [ ] #3989 - Implement bucket garbage collector, blocked by #3986;
- [ ] #3990 - Implement in-memory wal-free bucket references, blocked by #3986;
- [ ] #3991 - Implement bucket recovery fiber, blocked by #3986;
- [ ] #3992 - Implement bucket rebalancer, blocked by #3988.

## Router:
- [ ] #3993 - Allow proxy to connect to multiple replicasets, blocked by #2625;
- [ ] #3994 - Allow to specify bucket_id with any request on proxy, blocked by #3986;
- [ ] #3995 - Implement bucket routing table, bucket discovery, point lookup of bucket, blocked by #3994.
