### ISSUE TITLE
Leave Travis CI

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4894]
Before leaving we should close these issues:
- [x] need to move sources tarball creation from travis to gitlab #4895
- [ ] enable notifications on GitLab CI for release branches and master
- [x] move jobs from Travis CI to GitLab CI (at least with code coverage) #4893
- [x] need to implement packaging to packagecloud from gitlab to leave travis #4891

This issue should fix #4410, #1998?, #4377?, #1800?

**Comment by ligurio** [comment]
@Totktonada, @avtikhon, anything else?

**Comment by avtikhon** [comment]
Added sources tarball #4895

**Comment by Totktonada** [comment]
> need to implement packaging to packagecloud from gitlab to leave travis #4891

I think it is better to proceed with #4947.

> This issue should fix #4410, #1998?, #4377?, #1800?

* #4410 — yes.
* #1998 — no; the idea is to verify i386 build in CI. At the time of writing the issue we use Travis CI, so the wording mention it.
* #4377 — yes; but I would just push fix: it is simple, harmless and already exists.
* #1800 — no; the same as #1198 — it is not Travis CI specific.

**Comment by Totktonada** [comment]
I closed #4410, which becomes obsoleted. Cited the comment:

> Most of Travis CI jobs was moved to GitLab CI, but the last ones were moved to GitHub Actions (in the scope of #5294). The problem was finally closed in [7aa0b01](https://github.com/tarantool/tarantool/commit/7aa0b018726a651601c758228c8ad965135a29d0) ([full history](https://github.com/tarantool/tarantool/commits/master/.travis.yml)).
> 
> We're going to use GitHub Actions as the signle CI provider (so, moving from GitLab CI to GitHub Actions now).

I also closed issues you linked (ones that are actually relevant to the transition from Travis CI).

I guess there is nothing to track within this issue anymore. Feel free to reopen with details if I missed something.
