### ISSUE TITLE
Jepsen testing introduction: define quality metrics, tests

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5208]
For replication sake we should consider implement tests based on Jespen framework.

Major subtasks: 

- [x] Prepare a list of tests suitable for Serializable consistency model
- [x] Prepare a list of fault injections (nemeses) to use with Jepsen
- [x] Publish repository with Tarantool tests based on Jepsen
- [x] Create Terraform config #5277
- [x] Integrate Jepsen tests to GitLab CI to run tests per commit #5277
- [x] Implement nemeses (see https://github.com/tarantool/tarantool/issues/5208#issuecomment-684906558)
- [x] Implement support of different Tarantool versions to use with Jepsen tests: build by SHA commit (Debug and Release), latest version in a package repository, specific version in a package repository
- [ ] Implement tests suitable for Serializable consistency model (see https://github.com/tarantool/tarantool/issues/5208#issuecomment-684906558)
- [ ] Review a [list of fault injections](https://github.com/tarantool/tarantool/blob/master/src/lib/core/errinj.h#L73) and choose those that are suitable to use with Jepsen (resp. @sergos)
- [ ] Describe Tarantool features in common DBMS terms https://github.com/tarantool/doc/issues/1467 (resp. Doc Team)

Related tickets:

- RAFT implementation in Tarantool https://github.com/tarantool/doc/issues/1541#issuecomment-701703550
- Transaction engine for memtx engine #4897
- Raft: handle split-brain #5295
- Synchronized replication dirty reads #5229
- Raft: new leader should commit synchronous transactions from the previous leader #5339

**Comment by ligurio** [comment]
sergos@:

```
Fault injection на dirty read попробовать в тестах Jepsen.

1. Обязательно Debug сборка Тарантул.
2. В отдельном файбере ставим ERRINJ_WAL_DELAY и за ним запись в спейс - этот файбер повиснет после добавления записи
3. В исходном файбере читаем то, что вставляли в п.2
4. В исходном файбере (последовательно) выставляем ERRINJ_WAL_WRITE_DISK и снимаем ERRINJ_WAL_DELAY - получаем откат и п.3 становится грязным чтением

пример (сорри за лапидарность)

box.cfg{} box.schema.create_space('t'):create_index('p')
f1=require('fiber').new(function() box.error.injection.set('ERRINJ_WAL_DELAY', true) box.space.t:insert{3} end)
box.space.t:select{}
---
- - [3]
...
box.error.injection.set('ERRINJ_WAL_WRITE_DISK', true)
box.error.injection.set('ERRINJ_WAL_DELAY', false)
box.space.t:select{}
---
- []
...
```

**Comment by ligurio** [comment]
The Jepsen framework subjects the tests to a number of failure scenarios, rightfully called nemesis failures.
Possible fault injections:

- [ ] kill (SIGKILL) - kill and restart a randomly chosen database process that is a part of the cluster.
- [ ] partition - introduce network partitions into the cluster that isolates a randomly chosen node from the rest of the nodes in the cluster.
- [ ] partition-half - n/2+1 splits
- [ ] partition-one - isolate single nodes
- [ ] partition-ring - introducing network partitions dividing the cluster in two, or into overlapping rings of 3/5 nodes each, such that every node observed a majority, but no two nodes agreed on what that majority was.
- [ ] pause - process pauses (SIGSTOP)
- [ ] random-merge - merge partitions
- [ ] restart-replica-without-leader - restart replica when leader is not available
- [ ] shuffle-leader - randomly reassign leaders
- [ ] clock-skew - cover a range of issues related to the clock synchronization across different machines. There are a number of different clock skews introduced – small (~ 100ms), medium (~ 250ms), large (~ 500ms) and xlarge (~ 1 secs). Used libfaketime to simulate some node clocks, both CLOCK_REALTIME and CLOCK_MONOTONIC, running up to 5x faster than others.
- [ ] internal Tarantool set of `ERR_INJ`

Jepsen tests:

- [x] Single-Key Linearizable (Register)
- [ ] Multi-Key Linearizable
- [ ] Counter
- [ ] Delete
- [ ] Upsert
- [ ] Sets
- [ ] Append
- [ ] G2
- [ ] Bank
- [ ] Long fork
- [ ] Monotonic
- [ ] Multimonotonic
- [ ] Sequential

**Comment by ligurio** [comment]
This is a too general task for activity with testing Tarantool using Jepsen. Now we have a separate repository with Jepsen tests source code and all activity will be tracked there in a separate issues - https://github.com/tarantool/jepsen.tarantool/issues/.
Nothing to do here.
