### ISSUE TITLE
infra: verify tarantool changes against modules / connectors

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5265]
Tarantool version: 2.6.0-48-gbfeb61b33.

I propose to run existing tests from connectors / modules per tarantool change.

Below is the list of repositories I propose to enable first. It is based on my personal view of importance and popularity (how often users ask something around). We can add more repositories later, but let's hold scope of this issue and implement only this list for now.

Connectors (subtask: #4856):

- [x] [tarantool-c](https://github.com/tarantool/tarantool-c) (subtask: #6582)
- [x] [tarantool-python](https://github.com/tarantool/tarantool-python) (subtask: #6584)
- [x] [tarantool-php/client](https://github.com/tarantool-php/client) (subtask: #6594)
- [x] [tarantool-php/queue](https://github.com/tarantool-php/queue) (subtask: #6595)
- [x] [go-tarantool](https://github.com/tarantool/go-tarantool) (subtask: #6607)

Modules:

- [x] [vshard](https://github.com/tarantool/vshard) (subtask: #4972)
- [x] [avro-schema](https://github.com/tarantool/avro-schema) (subtask: #6558)
- [x] [queue](https://github.com/tarantool/queue) (subtask: #6559)
- [x] [expirationd](https://github.com/tarantool/expirationd) (subtask: #6528)
- [x] [smtp](https://github.com/tarantool/smtp) (subtask: #6523)
- [x] [mysql](https://github.com/tarantool/mysql) (subtask: #6577)
- [x] [checks](https://github.com/tarantool/checks) (subtask: #6562)
- [x] [metrics](https://github.com/tarantool/metrics) (subtask: #6526)
- [x] [memcached](https://github.com/tarantool/memcached) (subtask: #6563)
- [x] [cartridge](https://github.com/tarantool/cartridge) (subtask: #6512)

Other:

* [nginx_upstream_module](https://github.com/tarantool/nginx_upstream_module)

Deprecated modules:

I'm not sure whether it worth to test deprecated modules, but at least stat catches one backward incompatible change in the past.

* [stat](https://github.com/tarantool/stat) (past case: #4039)
* [prometheus](https://github.com/tarantool/prometheus)
* [graphite](https://github.com/tarantool/graphite)

**Comment by ligurio** [comment]
Looks like a duplicate of #4856.

**Comment by Totktonada** [comment]
Sorry, missed it. Added as the subtask.

Also added asynctnt and vviciious/go-tarantool into the list of connectors.

Regarding the C++ connetor: I would leave it out of scope here, because it is not implemented yet.

**Comment by igormunkin** [comment]
There is also a [good one for Perl](https://github.com/Mons/EV-Tarantool16) (I specified the fork repo, since there are several changes hasn't been upstreamed). AFAIR, It's also widely used.

**Comment by Totktonada** [comment]
See details in https://github.com/tarantool/tarantool/issues/6056#issuecomment-924026937.

**Comment by Totktonada** [comment]
https://github.com/actions/download-artifact is about transferring artifacts within a workflow. It seems, https://github.com/dawidd6/action-download-artifact should do the job. See discussions:

https://github.com/actions/download-artifact/issues/83
https://github.com/actions/download-artifact/issues/3

**Comment by Totktonada** [comment]
There is another idea: use the recently published `on.workflow_call` syntax. I'll cite my [comment](https://github.com/tarantool/vshard/pull/299/files#r724621435) about vshard side workflow:

> GitHub offers `on.workflow_call` recently ([docs](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows)). It is more like running steps from a called workflow within context of a caller workflow. It seems, it should resolve all those problems around passing artifacts from one workflow into another, waiting a child workflow run, downloading logs from the child workflow run.
>
> (We can write a workflow with a one job for building the package and a set of job that waits it (`needs`), which call the external workflows.)
>
> If it will allow us to write less code on the [caller side](https://github.com/tarantool/tarantool/pull/6488) (less code — less support work) and will not limit us in some way, it looks promising.
>
> Sorry, I was not aware of the new feature when we discussing the schema of testing of tarantool against vshard.

**Comment by ylobankov** [comment]
Looks like we are done here. Closing.
