### ISSUE TITLE
Implement exception handling on traces

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#5630]
LuaJIT embedded in Tarantool uses external unwinder based on [System V x86_64 ABI](https://www.uclibc.org/docs/psABI-x86_64.pdf) stack unwind algorithm (sec. 3.7). This machinery is used for error handling in all Lua universe and also is [interoperable with C++ exceptions](http://luajit.org/extensions.html). Unfortunately, everything works fine only for non-JIT-compiled paths according to the [status page](http://luajit.org/status.html). Strictly saying there is one more case except the mentioned out-of-memory (i.e. `LUA_ERRMEM` error type): C++ exceptions or Lua errors raised in the third party libraries routines, called via FFI, and propagated to LuaJIT runtime (see [this example](https://gist.github.com/igormunkin/e45597abfb34a69138a0c6042d710b80)).

To solve this issue we need to implement error unwinding for the JIT compiled code. Below is a sketch plan for RnD with the major points to be resolved.
* [ ] Implement `.eh_frame` info emitter to be used while trace recording and assembling phases (#5763).
* [ ] Introduce personality routine for compiled traces to be used in scope of search and cleanup unwinder phases.
* [ ] Both host and guest stacks should be consistent (at least, in terms that `debug.traceback` doesn't fail if called in `xpcall` handler) after unwinder search phase and prior to cleanup phase.
* [ ] There have to be "anchors" for inlined protected calls (i.e. calls via `pcall`/`xpcall`) where to leave the trace and proceed the further execution in VM (according to [Lua reference manual](https://www.lua.org/manual/5.1/manual.html#2.7)).

Related issues: #562, #843, #4506, #4671.

**Comment by filonenko-mikhail** [comment]
I like this post so much, even if Tarantool become slower 10x times

**Comment by igormunkin** [comment]
Epic is superseded with #7745.
