### ISSUE TITLE
Feedback and features enrich for memory profiler

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#5657]
In scope of #5442 there were an RFC and a MVP implemented.
We should collect users feedback and enrich the memory profiler API considering users demand.

UPD: tasks created after receiving feedback from users:
- [x] #5811 -- make the profiler output clearer 
- [x] #5812 -- add memprof `--leak-only` option

Follow-ups for 2.9.1 milestone:
- [x] #5813 -- demangling of C symbols
- [x] #5814 -- group allocation on traces by trace number
- [x] #5815 -- enrich symtab with newly created function prototypes

**Comment by kyukhin** [comment]
Done.
