### ISSUE TITLE
module: configuration provider (MVP)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5681]
Implement a client to a fault-tolerant key-value storage. Actual storage may be etcd, consul or a tarantool cluster. I propose to implement etcd driver in the scope of the MVP. Maybe also local or remote tarantool driver (assuming that replication is properly configured to afford fault tolerancy).

The main idea of the issue is to define API with the following properties:

* Independent of actual storage (tarantool, etcd, consul, ...).
* Extensible and versioned.
* Available locally from Lua, remotely via iproto (and remotely via http, maybe not as part of the MVP).

When we'll have more or less stable API, we'll able to lean on it in topology provider, database schema provider, service registry, authentication provider, automatic failover algorithms and so on.

Rough list of operations (to be carefully designed):

* read / get
* write / set
* cas
* lock with deadline and renewal
* subscription for updates with filtering
* log of changes since particular 'LSN'
* snapshot for particular 'LSN'

----

My roadmap (quite rough, may vary a lot):

* [x] etcd: initial working layout for ldoc / luatest
* [x] etcd: put request
* [x] etcd: range request + put / range tests
* [x] etcd: round robin + tests
* [x] common api: propose design
* [x] common api: get/set/del (flat and deep)
* [ ] common api: API changes by the product team feedback (partially)
* [x] common api: pre-publication bug hunting
* [x] publication (https://github.com/tarantool/conf)

----

Several points were in the original plan, but I postponed them for Q2'21:

* [ ] etcd: authorization + tests
* [ ] etcd: transactions
* [ ] etcd: lease
* [ ] common api: transactions
* [ ] common api: lease

**Comment by Totktonada** [comment]
I published the module in https://github.com/tarantool/conf

It is in early beta.
