### ISSUE TITLE
Consistent types across Lua and SQL data models

### ISSUE THREAD

**Issue by tsafin** [tarantool/tarantool#5817]
We need to make Lua and SQL types be consistent across data models. Making sure we use reasonable type conversion rules, and least surprising behaviour while transferring data between languages and and within module between functions.

Part 1:
- Consistent type conversion rules
  - [x] Create master table for type conversions Lua-SQL-MP-box #5847
  - [x] Refactor SQL code and centralize mem-type fields control (via getter and setters introduced). This helps to prepare to sql types commonization #5818;
  - [x] Implement "define rules for comparison for SCALAR" #5148
  - [x] SQL arithmetic types are broken #4470 - fix it!
  - [x] Explicit cast from VARBINARY to DOUBLE sometimes works incorrectly #5852
- [x] Introduce UUID type support in SQL #5886
- [x] Introduce DATETIME type to Tarantool  #5941
- [x] Implement Decimal type in SQL #4415

Part 2:
- [ ] Check "Preserve cdata type in tonumber64" #4738
- [x] ARRAY support #4762 (simpler way), proper way - TBD
- [x] MAP support #4763 (simpler way), proper way - TBD

**Comment by filonenko-mikhail** [comment]
Bare metal sizes optional request

**Comment by kyukhin** [comment]
Most is done. The remaining issue goes to the next MS.
