### ISSUE TITLE
Introduce TIMESTAMP type to Tarantool

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#5941]
Most of modern DBMS contain such a type. Let's do that as well.

Need to:
- [x] Add new extensions to Msgpack https://github.com/tarantool/tarantool/issues/5946
- [x] (possibly) re-use icu-date for manipulation routines #5947
- [x] Olson/timezones database support #6751
- [x] Add datetime types support to SQL (#6773, #3694)

**Comment by mumez** [comment]
MessagePack specification now has a Timestamp extension type. So I think it would be worth looking at the section.
https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type

**Comment by tsafin** [comment]
@mumez 
> MessagePack specification now has a Timestamp extension type. So I think it would be worth looking at the section.
> https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type

Yes, I was aware of this extension, but there were a couple of problems:
- it was not including timezone (we have to support it for SQL `TIMESTAMP WITH TIME ZONE` type);
- and it's not elastic and compact enough for small values of seconds/nanoseconds.

At the moment we plan to use different MP_EXT-based encoding https://github.com/tarantool/tarantool/discussions/6244#discussioncomment-1043990
