### ISSUE TITLE
Make tarantool ecosystem CI / CD great again

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6056]
Everything below is actually about maintenance costs. They becomes too high for our small team, so we need to resolve considerable amount of the technical debts to effectively pay our time for development and maintenance of the ecosystem around tarantool.

It worth to note that everything below is actually the bare minimum we need for a normal development process. I can point other ares for testing improvements, but I want to reduce focus on the most important things within the scope of this issue.

### Testing of a module / a connector / a tool

We have a lot of modules, connectors and tools for tarantool. Many of them have obvious problems around CI / CD:

- No CI / CD at all or on Travis-CI, which effectively becomes a paid service (.org infrastructure will gone soon, .com have tight limits) and does not work for us anymore.
- CI against just one tarantool version.
- CI against just one OS (one Linux distro, no Mac OS).
- CI, which verifies only a development flow (`cmake . && make && make test`), not a user scenario:
  - Install a module using an RPM / Deb package, run tests.
  - Install a module using tarantoolctl rocks, run tests.
- No RPM / Deb packages deployments or deployments to the old PackageCloud infrastructure (see #3380, #4947, #5494).
- No rockspec deployments to rocks.tarantool.org (especially for tagged versions).

All those flaws leads to spending extra time as from a contributor as well as from a maintainer to verify the changes. It makes the development around tarantool ecosystem less attractive.

### CI maintenance

There are less obvious problems around obsolescense of CI / CD itself: we should keep it actual in the long terms across many repositories. My list here is the following:

- We should run testing against (at least) fresh tarantool versions and push packages to actual tarantool repositories (they're splitted per release series such as 2.7, 2.8, which spawned four times per year).
- We should run testing and deployment against an actual list of supported OS (say, Fedora is released twice per year).

Manual updating of the testing / deployment matrix within each repository is not only tiresome. It just does not work in the long terms: humans unable to do this work on a regular basis. CI / CD should have **zero** maintenance effort, at least in context of such values, that are known to obsolete regularly.

### Tarantool testing against ecosystem

Usually CI of a module / a connector / a tool verifies changes in its repository. However it is not the only type of feedback we want to receive from this CI:

- Aside of testing of a module (a connector / a tool) itself, we should be able to test a new tarantool revision against all of them.

It is especially important before releasing a new version of tarantool.

## Burndown

Automate and speed up tarantool installation in CI: [setup-tarantool](https://github.com/tarantool/setup-tarantool).

- [ ] Support live repositories (per push tarantool builds) (https://github.com/tarantool/setup-tarantool/issues/9)
- [ ] Support Mac OS (https://github.com/tarantool/setup-tarantool/issues/10)
- [ ] Support self-hosted Linux runners (non-Ubuntu Linux distributions) (https://github.com/tarantool/setup-tarantool/issues/11)
- [ ] Add meagingful aliases for numeric tarantool versions (https://github.com/tarantool/setup-tarantool/issues/12)
- [ ] Choose exact release (such as 2.5.1) (https://github.com/tarantool/setup-tarantool/issues/15)

In fact those tasks may be solved in each repository individually (just like [here](https://github.com/tarantool/smtp/pull/30)), but it'll increase copy-paste across different repositories (worse in maintenance), likely will negatively impart CI duration.

----

Automate deployments: [rws](https://github.com/tarantool/rws).

- [ ] [blocker] Add possibility to sign a repository with a GPG key (https://github.com/tarantool/rws/issues/3)
- [ ] [blocker] Deploy service to Heroku (https://github.com/tarantool/rws/issues/9)
- [ ] infra: implement RPM / Deb packages listings (https://github.com/tarantool/rws/issues/10)
- [ ] Implement transactional package upload (https://github.com/tarantool/rws/issues/2)
- [ ] Add to README a description of the guarantees uploading package into repo (https://github.com/tarantool/rws/issues/4)
- [ ] Add tests for the service (https://github.com/tarantool/rws/issues/5)
- [ ] Add logging to the service (https://github.com/tarantool/rws/issues/6)
- [ ] Implement "synchronization" of all repositories on start the service (https://github.com/tarantool/rws/issues/7)
- [ ] Create a tool for backup repositories (https://github.com/tarantool/rws/issues/8)
- [ ] Support a credential with a reduced scope (https://github.com/tarantool/rws/issues/11)

Some of those tasks are necessary for maintain the service itself in the long terms: we can skip them now, but it is undesirable to leave them unresolved at all.

----

Create a set of GitHub Workflows that will resolve typical problems. This part is likely will be quite similar across different repositories, but will have some module/connector/tool specific peculiars (say, testing on using mysql versions for the mysql module or on different python versions for the python connector).

The checklist here is the first list of problems in the first section ('Problems'). Some code may be written once in setup-tarantool. Some will require copying and adoption. Maybe it is possible to find more points of unification.

I'll list tasks in the smtp module as example, but it should be applied to each module or connector listed below:

- [ ] Setup initial CI (https://github.com/tarantool/smtp/pull/30)
- [ ] Verify RPM / Deb packages using GitHub Actions (https://github.com/tarantool/smtp/issues/34)
- [ ] [for modules] Verify tarantoolctl rocks installation in CI (https://github.com/tarantool/smtp/issues/35)
- [ ] Deploy the module (RPM / Deb) from GitHub Actions (https://github.com/tarantool/smtp/issues/36)
- [ ] [for modules] Deploy a rockspec from GitHub Actions (https://github.com/tarantool/smtp/issues/37)

----

There are problems, which should be resolved, but I don't know how and where exactly.

- [ ] Populate tarantool versions matrix with recent tarantool releases and / or latest live versions (use [fromJSON()](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions), store the list somewhere around rws?).
- [ ] Populate OS matrix with systems supported by tarantool (use [fromJSON()](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions), store the list somewhere around rws?).
- [ ] Verify a particular tarantool commit against all modules / connectors / tools (use [workflow_dispatch / repository_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events), collect results by an external script, generate a webpage with results?).

## The list of modules

Ones that're created within the server team, so we have a reponsibility for them.

- [ ] 1. [avro-schema](https://github.com/tarantool/avro-schema)
- [ ] 2. [conf](https://github.com/tarantool/conf)
- [ ] 3. [dump](https://github.com/tarantool/dump)
- [ ] 4. [expirationd](https://github.com/tarantool/expirationd)
- [ ] 5. [gis](https://github.com/tarantool/gis)
- [ ] 6. [gperftools](https://github.com/tarantool/gperftools)
- [ ] 7. [httpng](https://github.com/tarantool/httpng)
- [ ] 8. [memcached](https://github.com/tarantool/memcached)
- [ ] 9. [moonwalker](https://github.com/tarantool/moonwalker)
- [ ] 10. [mqtt](https://github.com/tarantool/mqtt)
- [ ] 11. [mysql](https://github.com/tarantool/mysql)
- [ ] 12. [pg](https://github.com/tarantool/pg)
- [ ] 13. [queue](https://github.com/tarantool/queue)
- [ ] 14. [s3](https://github.com/tarantool/s3)
- [ ] 15. [smtp](https://github.com/tarantool/smtp)
- [ ] 16. [synchronized](https://github.com/tarantool/synchronized)
- [ ] 17. [tuple-keydef](https://github.com/tarantool/tuple-keydef)
- [ ] 18. [tuple-merger](https://github.com/tarantool/tuple-merger)
- [ ] 19. [vshard](https://github.com/tarantool/vshard)
- [ ] 20. [topology](https://github.com/tarantool/topology)

## The list of connectors

Again, ones that're created within the server team or should receive considerable level of support from us.

- [ ] 1. [go-tarantool](https://github.com/tarantool/go-tarantool)
- [ ] 2. [node-tarantool-driver](https://github.com/tarantool/node-tarantool-driver)
- [ ] 3. [tarantool-c](https://github.com/tarantool/tarantool-c)
- [ ] 4. [tarantool-erlang](https://github.com/tarantool/tarantool-erlang)
- [ ] 5. [tarantool-java](https://github.com/tarantool/tarantool-java)
- [ ] 6. [tarantool-lua](https://github.com/tarantool/tarantool-lua)
- [ ] 7. [tarantool-perl](https://github.com/tarantool/tarantool-perl)
- [ ] 8. [tarantool-php](https://github.com/tarantool/tarantool-php)
- [ ] 9. [tarantool-python](https://github.com/tarantool/tarantool-python)
- [ ] 10. [tarantool-ruby](https://github.com/tarantool/tarantool-ruby)
- [ ] 11. [tntcxx](https://github.com/tarantool/tntcxx)

And I would also include addons of some kinds here (not everything above is applicable for them):

- [ ] 1. [queue-python](https://github.com/tarantool/queue-python)
- [ ] 2. [tarantool-jcache](https://github.com/tarantool/tarantool-jcache)
- [ ] 3. [tarantool-php-stubs](https://github.com/tarantool/tarantool-php-stubs)

**Comment by Totktonada** [comment]
NB: It also worth to update [modulekit](https://github.com/tarantool/modulekit) and possibly convert it to a [template repository](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/).

**Comment by Totktonada** [comment]
There was a discussion how we want to test tarantool changes against modules / connector. The short summary is the following:

* Test on `ubuntu-latest` (20.04, Focal Fossa). No other Linux distributions, no Mac OS[^1].
* Test on `master` branch of the module / connector. No other module / connector releases[^2].
* Run automatically per push to `master` and release branches in tarantool/tarantool. Allow to run manually on a development branch in tarantool/tarantool.
* Tarantool side workflow should perform the following steps:
    - Set 'in progress' status on the commit for each target (it corresponds to a module / a connector) using the checks API.
    - Build tarantool package for Ubuntu Focal and store it in job artifacts.
    - Trigger necessary module / connector workflows. It'll download the artifact and run tests on given tarantool.
    - Wait for results and set the status using the checks API.

Footnotes:

[^1]: We actually want to verify tarantool against public API breakage. So one Linux distro should be enough.

[^2]: An old release may lack of support for the new tarantool versions. Say, due to usage of some undocumented behaviour (see https://github.com/tarantool/vshard/issues/294 for example).

**Comment by rybakit** [comment]
> Test on master branch of the module / connector. No other module / connector releases[^2].

If the purpose of this initiative is to make sure that any new changes to tarantool do not break existing functionality, then master is probably not the best option because connectors/modules can introduce their own bugs into master, depending on their release cycle. So maybe testing on the latest stable release (if available) makes more sense? If the goal is to test changes at an early stage for both tarantool *and* connectors/modules, then master is indeed the way to go.

**Comment by Totktonada** [comment]
> > Test on master branch of the module / connector. No other module / connector releases[^2].
> 
> If the purpose of this initiative is to make sure that any new changes to tarantool do not break existing functionality, then master is probably not the best option because connectors/modules can introduce their own bugs into master, depending on their release cycle. So maybe testing on the latest stable release (if available) makes more sense? If the goal is to test changes at an early stage for both tarantool _and_ connectors/modules, then master is indeed the way to go.

@rybakit Testing on master should be good enough for us, while it is easier in maintenance. An incompatible change in a module/connetors will likely be spotted by CI in the module/connector before pushing a patch to the module.
