### ISSUE TITLE
Master-discovering support

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#6256]
There are a lot of projects that require master-discovering.
Our projects are:
- vshard
- cartridge
- topology service (in future)
 
Also, users, who learned about RAFT inside tarantool, usually ask: "How to discover the master with the technology?".

So we need to extract the module(s) as a tarantool's system technology.

I think that the epic issue must include the following tasks:

- [ ] Provide light pub/sub technology in tarantool.
- [ ] Add a few predefined system events for pub/sub:
  - Readonly status.
  - RAFT term.
  - Graceful shutdown status.
  - etc
- [ ] Master-discovering mechanism mustn't require any grants to work.
- [ ] LUA module "net.replicaset" that have the following abilities:
  - Execute a request at ANON, RO or MASTER node.
  - Detect 'where is the master?' with minimal lag.
  Also
  - Switch traffic between nodes by their weights and zones.
- [ ] Add the functional into Golang, Python and Java connectors.
- [ ] Update the documentation in order to allow users writing their connectors using the technology.

**Comment by Mons** [comment]
Anon/ro/master is not sufficient.

There are also policies: anywhere, but prefer master (arw) and anywgere but prefer replica (aro)

**Comment by R-omk** [comment]
related https://github.com/tarantool/tarantool/issues/2625

as an option,  can make it so that any node could be process rw requests (but make an internal redirect to the real master), and can add information to the iproto that the request was actually executed on another node.
