### ISSUE TITLE
libunwind submodule follow-up fixes

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#6998]
After reviewing #6877, @Totktonada proposed some suggestions and fixes:
```[tasklist]
### Tasks
- [x] return _autotools_ to _RHEL_ and _debian_ distribution dependencies;
- [x] remove _backtrace_ feature compiler dependency from [_rpm spec_](https://github.com/tarantool/tarantool/blob/master/rpm/tarantool.spec);
- [x] fix _libunwind_ submodule [changelog](https://github.com/tarantool/tarantool/blob/master/changelogs/unreleased/add-libunwind-submodule.md): license and _backtrace_ feature compiler dependency in _rpm spec_;
- [x] clarify compatibility of _libunwind_ and _Tarantool_ with compressed debug symbols;
- [x] add _libunwind_ license to [_debian/copyright_](https://github.com/tarantool/tarantool/blob/master/debian/copyright);
- [x] remove __libunwind__ package depencies from _rpm spec_ and [_debian/control_](https://github.com/tarantool/tarantool/blob/master/debian/control).
- [x] Re-verify elimination of `-DCMAKE_FIND_USE_CMAKE_SYSTEM_PATH=FALSE` (https://github.com/tarantool/tarantool/pull/6877#discussion_r936010410)
```

**Comment by H9660** [comment]
I can fix this issue considering my expertise. Please assign it to me.

**Comment by H9660** [comment]
Thanks for assigning me this

**Comment by Totktonada** [comment]
@CuriousGeorgiy Is it planned for the upcoming release?

**Comment by CuriousGeorgiy** [comment]
@Totktonada please address this to @alyapunov.

**Comment by Totktonada** [comment]
We have bundled libunwind based on [this](https://github.com/libunwind/libunwind/commit/879ad87300a12f70c365fc16592c94cdf9f07d86) upstream revision. It is reported by `git describe --tags` as v1.5-rc1-112-g879ad873. The branch in our [downstream](https://github.com/tarantool/libunwind) is named `libunwind-1.6.2-tarantool`, but it does not seems to be v1.6.2.

@CuriousGeorgiy Can you clarify, whether it is a mistake or I missed something? Whether the idea was to bundle the latest release (v1.6.2)?

**Comment by CuriousGeorgiy** [comment]
@Totktonada yes, the idea was to bundled the latest release.

**Comment by CuriousGeorgiy** [comment]
@Gumix While you are here, could please fix this warning?

```console
CMake Warning (dev) at /Users/georgiy.lebedev/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-2/231.8109.222/CLion.app/Contents/bin/cmake/mac/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (GetLIBUNWINDVersion.cmake) does not match the name of the calling package
  (LibUnwind).  This can lead to problems in calling code that expects
  `find_package` result variables (e.g., `_FOUND`) to follow a certain
  pattern.
Call Stack (most recent call first):
  cmake/FindLibUnwind.cmake:82 (find_package_handle_standard_args)
  CMakeLists.txt:552 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Looks like a one liner typo.
