### ISSUE TITLE
Datetime followups

### ISSUE THREAD

**Issue by tsafin** [tarantool/tarantool#7176]
Bugs/features
==========
- [ ] Datetime miscalculations for some dates (A - B + B != A) #7145;
- [ ] Do not mess with nanoseconds, output as is - #7045;
- [ ] MessagePack decoder does not validate values #6723;
- [ ] datetime crash on invalid msgpack #6722;
- [ ] Consider to extend supported date raneg to 'Max year 142710460 and min year -142710460' as in RFC. (Debatable);
- [ ] Make '%F%%T %Z' be more compatible with default tostring() format (as it was requested by RFC). %Z format should be extended both in strftime and strptime to make it behave consistently for teh case when tzindex not used;

Build:
- [ ] build: get rid of manual tnt_ wrappers #6720;
- [ ] Get rid of src/lib/tzcode/tz for the insourec build - #7173;

Performance
==========
- [ ] Messagepack serialization benchmark - #6940, #6504;
- [ ] Use more than single caching entry in lookaside buffer for timezone entries;

Documentation
===========
- [ ] Wiki - There are no explanations of how to use DATETIME/INTERVAL from SQL side;
- [  ] Wiki - No documentation for INTERVAL MessagePack serialization;
