### ISSUE TITLE
Backporting LuaJIT upstream commits part 2

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#7230]
This ticket is an umbrella for all commits we planning to back-port in the next Q.
This list includes commits excluded from #6548 and may be updated later with some new.

Unwinding on M1 and prerequisites:
* [x] [e1319361](https://github.com/LuaJIT/LuaJIT/commit/e1319361) Cleanup and enable external unwinding for more platforms.
* [x] [d4a554d6](https://github.com/LuaJIT/LuaJIT/commit/d4a554d6) OSX: Fix build by hardcoding external frame unwinding.
* [x] [27ee3bcd](https://github.com/LuaJIT/LuaJIT/commit/27ee3bcd) OSX/ARM64: Disable external unwinding for now.
* [x] [421c4c79](https://github.com/LuaJIT/LuaJIT/commit/421c4c79) ARM64: Reorder interpreter stack frame and fix unwinding.
* [x] [78350a25](https://github.com/LuaJIT/LuaJIT/commit/78350a25) OSX/ARM64: Disable unwind info.
* [x] [b9d52396](https://github.com/LuaJIT/LuaJIT/commit/b9d52396) BSD: Fix build with BSD grep.
* [x] [66563bda](https://github.com/LuaJIT/LuaJIT/commit/66563bda) Fix build with busybox grep.
* [x] [bfcb74ed](https://github.com/LuaJIT/LuaJIT/commit/bfcb74ed) OSX/ARM64: Fix external unwinding. (#6096)

general + x86/x64:
* [x] [b4ed3219](https://github.com/LuaJIT/LuaJIT/commit/b4ed3219) LJ_GC64: Fix ir_khash for non-string GCobj.
* [x] [05fbdf56](https://github.com/LuaJIT/LuaJIT/commit/05fbdf56) x64/LJ_GC64: Fix type-check-only variant of SLOAD.
* [x] [b5b20191](https://github.com/LuaJIT/LuaJIT/commit/b5b20191) Save trace recorder state around VM event call. (#6782)
* [x] [ca8d3257](https://github.com/LuaJIT/LuaJIT/commit/ca8d3257) Ensure correct stack top for OOM error message.
* [x] [0913b16e](https://github.com/LuaJIT/LuaJIT/commit/0913b16e) Fix handling of errors during snapshot restore.
* [x] [de8e88b0](https://github.com/LuaJIT/LuaJIT/commit/de8e88b0) Call error function on rethrow after trace exit.
* [x] [fb5e522f](https://github.com/LuaJIT/LuaJIT/commit/fb5e522f) x86/x64: Check for jcc when using xor r,r in emit_loadi().
* [x] [a5a89ab5](https://github.com/LuaJIT/LuaJIT/commit/a5a89ab5) From Lua 5.3: assert() accepts any type of error object. (#7457)
* [x] [6bda30d8](https://github.com/LuaJIT/LuaJIT/commit/6bda30d8) LJ_GC64: Fix IR_VARG offset for fixed number of results. 
* [x] [8430f774](https://github.com/LuaJIT/LuaJIT/commit/8430f774) Fix io.close().
* [x] [d87da3d5](https://github.com/LuaJIT/LuaJIT/commit/d87da3d5) Fix io.close() error message. 
* [x] [02b52198](https://github.com/LuaJIT/LuaJIT/commit/02b52198) FFI: Add tonumber() specialization for failed conversions.
* [x] [179cf2eb](https://github.com/LuaJIT/LuaJIT/commit/179cf2eb) Fix overflow check in unpack().
* [x] [cc4bbec4](https://github.com/LuaJIT/LuaJIT/commit/cc4bbec4) FFI: Always fall back to metamethods for cdata length/concat. 
* [x] [1e6e8aaa](https://github.com/LuaJIT/LuaJIT/commit/1e6e8aaa) Fix narrowing of unary minus. (#6976)
* [x] [d75e2627](https://github.com/LuaJIT/LuaJIT/commit/d75e2627) Don't compile math.modf() anymore.
* [x] [5655be45](https://github.com/LuaJIT/LuaJIT/commit/5655be45) Cleanup math function compilation and fix inconsistencies.

**Comment by igormunkin** [comment]
All mentioned patches are backported. More patches will be backported in scope of  #8069.
