### ISSUE TITLE
Introduce subsystem performance benchmarks

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#7338]
There are a lot of interesting things to be done in terms of optimizations, but they are meaningless without corresponding benchmarks. We have kind of complex benchmarks emulating user's workload like [tpc-c](https://github.com/tarantool/tpcc), but only one perf test benchmarking low level thing (`perf/tuple.cc`). It is worth noting that we have already set up google benchmark lib, so we can write&launch nice benches (or adopt/port already existing - but check license compatibility first). What benchmarks should be done (TBC):
Data structures:

- [ ] 1. Hash table (`light.cc`);
- [ ] 2. BTree;
- [ ] 3. BitMap;
- [ ] 4. Rope;
- [ ] 5. Vinyl tuple cache.

Allocators:

- [ ] - Attempt to replace malloc with jemalloc/mimalloc (also see https://github.com/tarantool/tarantool/issues/2705);
- [ ] - Slabs + matras.

Subsystems (we can use c++ connector):

- [ ] - IProto (also see https://github.com/tarantool/tarantool/issues/4876);
- [ ] - Vinyl (also see https://github.com/tarantool/tarantool/issues/2400, https://github.com/tarantool/tarantool/issues/3588);
- [ ] - Tuple updates.

Also perf related issues:
https://github.com/tarantool/tarantool/issues/5492
https://github.com/tarantool/tarantool/issues/5659

**Comment by Korablev77** [comment]
Results for Light:
 - values: we use structure (tuple) containing pointer to heap memory
           and size (all payload is of the same size - 32 bytes);
 - keys: unsigned char (first byte in the tuple memory);
 - hash function: FNV-1a;
 - value comparator: std::memcmp();
 - value count: 10k - 100k - 1M

Here's the list of results obtained on my PC (i7-8700 12 X 4600 MHz):

```
Insertions: ~5M per second;
Find (no misses): ~20-14M* per second (find by key gives the same result);
Find (many misses): ~17M per second;
Iteration with dereference: ~300M per second;
Insertions after erase: ~23-9M* per second;
Find after erase: ~20-14M* per second (the same as without erase);
Delete: ~20-7M* per second.

* The first value is for 10k values in hash table; second - is for 1M.

Just to have some baseline here results for quite similar benchmark for
std::unordered_map (it is also included in source file):

Insertions: ~4-5M per second;
Find (no misses): ~21-12M per second;
Iteration with dereference: ~27-42M per second;
Find after erase: ~16-13M per second.
```

**Comment by CuriousGeorgiy** [comment]
@Korablev77 could you please open a separate ticket for each data structure to present results there?

**Comment by CuriousGeorgiy** [comment]
I think we could also draw inspiration from https://github.com/google/fleetbench.
