### ISSUE TITLE
Compat module followups

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8118]
This is a meta-issue for compat module followups (#7000):
- [x] https://github.com/tarantool/tarantool/issues/7883
- [x] https://github.com/tarantool/tarantool/issues/8033
- [x] https://github.com/tarantool/tarantool/issues/8115
- [x] https://github.com/tarantool/tarantool/issues/8117
