### ISSUE TITLE
config: upgrade credentials

### ISSUE THREAD

**Issue by Lord-KA** [tarantool/tarantool#8967]
Right now, credentials support is very primitive, it allows to create users and roles from config, assign them privileges (`read`, `write`, etc) for `universe` (meaning all objects), and "inherit" roles. For the full [access control](https://www.tarantool.io/en/doc/latest/book/admin/access_control/) functionality the following should be implemented:

```[tasklist]
- [x] Synchronization of privileges and role "inheritance" between current box configuration and config (#8968)
- [x] Remove hashes from schema (#8997)
- [x] Password sync for users (#8997)
- [x] Add test that users/roles are not deleted when removed from config (https://github.com/tarantool/tarantool/pull/9088)
- [x] Set privileges in a "lazy" way using triggers (e.g. on space/function/sequence rename or creation) (https://github.com/tarantool/tarantool/pull/9151)
- [x] Update privileges when instance goes from Read Only state to Read Write (https://github.com/tarantool/tarantool/pull/9119)
- [x] Add alerts when privileges can't be set for some reason (e.g. instance is in Read Only state) (https://github.com/tarantool/tarantool/pull/9208)
- [ ] ~Add example config for credentials~ Postponed
- [x] Add support for `lua_eval`, `lua_call`, `sql` object types. (https://github.com/tarantool/tarantool/pull/9231)
```

**Comment by Totktonada** [comment]
All the code tasks are done. I'll track the example enhancements separately. Closing so.
