### ISSUE TITLE
synchronous replication todo

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#980]
- [ ] wrap up bootstrap in the initial state
- [ ] code review fixes
- [ ] basic functional tests
- [ ] error injection tests
- [ ] functional tests and fixes for master roll back on conflict
- [ ] functional tests for slave rollback 
- [ ] function tests for slave reconnect after a timeout
- [ ] functional tests for re-election on master shutdown
- [ ] function tests for 3-2-1-0-1-2-3 restart of the cluster
- [ ] cbus
- [ ] generic implementation of iproto client library in C

**Comment by rtsisyk** [comment]
bsync tickets: https://github.com/tarantool/tarantool/labels/bsync

**Comment by GeorgyKirichenko** [comment]
To implement synchronous replication we have to do following tasks:
- [ ] replication from memory
- [ ] move relay reader to wal thread
- [ ] wal-tx cbus refactoring - to allow individual journal request commit/rollback
- [ ] xlog vclock commit/reject record which points vclock range acked/nacked
- [ ] recovery vclock ack/nack
- [ ] applier(replication) ack-nack processing
- [ ] wal redundancy - gather replica's statuses and generate acks/nacks
