### ISSUE TITLE
Protobuf encoder/decoder tasklist

### ISSUE THREAD

**Issue by Col-Waltz** [tarantool/tarantool#9844]
This is a tasklist for protobuf encoder/decoder module for gRPC protocol.

API for this module is described here https://www.notion.so/tarantool/RFC-Protocol-Buffers-encoder-decoder-17ff2ff599974f9a9d0f39d9ab0a5284?pvs=4

These tasks are arranged in which they will be done and may be separated in smaller one if needed. Feedback on the module development is welcome
```[tasklist]
### Tasks
- [ ] Four basic protobuf types encoder: https://github.com/tarantool/tarantool/pull/9488
- [ ] Repeated fields support for encoding
- [ ] Protobuf decoder
- [ ] .proto file parser
- [ ] Tarantool specific types (Timestamp, Userdata) supported
```

**Comment by R-omk** [comment]
As part of the ongoing development of the protobuf ecosystem, I propose adding support for `optional` fields in proto3. Optional fields allow for more efficient data serialization and better backward compatibility, especially in use cases where field presence or absence is important but not always guaranteed.

example

```proto
syntax = "proto3";

message MessageFromJson {

    string k1 = 1;
    optional string k2 = 2;

}
```

fields that are not present in the serialized representation will have different representations in memory.
